export const keyboardRussian = [
  {
    "key": "ё",
    "shiftKey": "Ё",
    "code": "Backquote",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "1",
    "shiftKey": "!",
    "code": "Digit1",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "2",
    "shiftKey": "\"",
    "code": "Digit2",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "3",
    "shiftKey": "№",
    "code": "Digit3",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "4",
    "shiftKey": ";",
    "code": "Digit4",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "5",
    "shiftKey": "%",
    "code": "Digit5",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "6",
    "shiftKey": ":",
    "code": "Digit6",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "7",
    "shiftKey": "?",
    "code": "Digit7",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "8",
    "shiftKey": "*",
    "code": "Digit8",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "9",
    "shiftKey": "(",
    "code": "Digit9",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "0",
    "shiftKey": ")",
    "code": "Digit0",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "-",
    "shiftKey": "_",
    "code": "Minus",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "=",
    "shiftKey": "+",
    "code": "Equal",
    "row": "1",
    "group": "alphanumeric",
  },
  {
    "key": "Backspace",
    "code": "Backspace",
    "row": "1",
    "group": "editing",
  },
  {
    "key": "Tab",
    "code": "Tab",
    "row": "2",
    "group": "control",
  },
  {
    "key": "й",
    "code": "KeyQ",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "ц",
    "code": "KeyW",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "у",
    "code": "KeyE",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "к",
    "code": "KeyR",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "е",
    "code": "KeyT",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "н",
    "code": "KeyY",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "г",
    "code": "KeyU",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "ш",
    "code": "KeyI",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "щ",
    "code": "KeyO",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "з",
    "code": "KeyP",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "х",
    "code": "BracketLeft",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "ъ",
    "code": "BracketRight",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "\\",
    "shiftKey": "/",
    "code": "Backslash",
    "row": "2",
    "group": "alphanumeric",
  },
  {
    "key": "Del",
    "code": "Delete",
    "row": "2",
    "group": "editing",
  },
  {
    "key": "CapsLock",
    "code": "CapsLock",
    "row": "3",
    "group": "control",
  },
  {
    "key": "ф",
    "code": "KeyA",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "ы",
    "code": "KeyS",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "в",
    "code": "KeyD",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "а",
    "code": "KeyF",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "п",
    "code": "KeyG",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "р",
    "code": "KeyH",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "о",
    "code": "KeyJ",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "л",
    "code": "KeyK",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "д",
    "code": "KeyL",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "ж",
    "code": "Semicolon",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "э",
    "code": "Quote",
    "row": "3",
    "group": "alphanumeric",
  },
  {
    "key": "Enter",
    "code": "Enter",
    "row": "3",
    "group": "control",
  },
  {
    "key": "Shift",
    "code": "ShiftLeft",
    "row": "4",
    "group": "control",
  },
  {
    "key": "я",
    "code": "KeyZ",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "ч",
    "code": "KeyX",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "с",
    "code": "KeyC",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "м",
    "code": "KeyV",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "и",
    "code": "KeyB",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "т",
    "code": "KeyN",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "ь",
    "code": "KeyM",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "б",
    "code": "Comma",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "ю",
    "code": "Period",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": ".",
    "shiftKey": ",",
    "code": "Slash",
    "row": "4",
    "group": "alphanumeric",
  },
  {
    "key": "Shift",
    "code": "ShiftRight",
    "row": "4",
    "group": "control",
  },
  {
    "key": "Ctrl",
    "code": "ControlLeft",
    "row": "5",
    "group": "control",
  },
  {
    "key": "Win",
    "code": "MetaLeft",
    "row": "5",
    "group": "control",
  },
  {
    "key": "Alt",
    "code": "AltLeft",
    "row": "5",
    "group": "control",
  },
  {
    "key": "",
    "code": "Space",
    "row": "5",
    "group": "space",
  },
  {
    "key": "Alt",
    "code": "AltRight",
    "row": "5",
    "group": "control",
  },
  {
    "key": "◀",
    "code": "ArrowLeft",
    "row": "5",
    "group": "cursor-control",
  },
  {
    "key": "▲",
    "code": "ArrowUp",
    "row": "5",
    "group": "cursor-control",
  },
  {
    "key": "▼",
    "code": "ArrowDown",
    "row": "5",
    "group": "cursor-control",
  },
  {
    "key": "▶",
    "code": "ArrowRight",
    "row": "5",
    "group": "cursor-control",
  },
  {
    "key": "Ctrl",
    "code": "ControlRight",
    "row": "5",
    "group": "control",
  },
];