export const keyboardRussian = [
    {
        "key": "ё",
        "keyCode": "192",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "1",
        "keyCode": "49",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "2",
        "keyCode": "50",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "3",
        "keyCode": "51",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "4",
        "keyCode": "52",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "5",
        "keyCode": "53",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "6",
        "keyCode": "54",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "7",
        "keyCode": "55",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "8",
        "keyCode": "56",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "9",
        "keyCode": "57",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "0",
        "keyCode": "48",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "-",
        "keyCode": "189",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "=",
        "keyCode": "187",
        "row": "1",
        "group": "alphanumeric",
    },
    {
        "key": "Backspace",
        "keyCode": "8",
        "row": "1",
        "group": "editing",
    },
    {
        "key": "Tab",
        "keyCode": "9",
        "row": "2",
        "group": "control",
    },
    {
        "key": "й",
        "keyCode": "81",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "ц",
        "keyCode": "87",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "у",
        "keyCode": "69",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "к",
        "keyCode": "82",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "е",
        "keyCode": "84",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "н",
        "keyCode": "89",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "г",
        "keyCode": "85",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "ш",
        "keyCode": "73",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "щ",
        "keyCode": "79",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "з",
        "keyCode": "80",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "х",
        "keyCode": "219",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "ъ",
        "keyCode": "221",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "\\",
        "keyCode": "220",
        "row": "2",
        "group": "alphanumeric",
    },
    {
        "key": "Del",
        "keyCode": "46",
        "row": "2",
        "group": "editing",
    },
    {
        "key": "CapsLock",
        "keyCode": "20",
        "row": "3",
        "group": "control",
    },
    {
        "key": "ф",
        "keyCode": "65",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "ы",
        "keyCode": "83",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "в",
        "keyCode": "68",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "а",
        "keyCode": "70",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "п",
        "keyCode": "71",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "р",
        "keyCode": "72",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "о",
        "keyCode": "74",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "л",
        "keyCode": "75",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "д",
        "keyCode": "76",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "ж",
        "keyCode": "186",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "э",
        "keyCode": "222",
        "row": "3",
        "group": "alphanumeric",
    },
    {
        "key": "Enter",
        "keyCode": "13",
        "row": "3",
        "group": "control",
    },
    {
        "key": "Shift",
        "keyCode": "16",
        "row": "4",
        "group": "control",
    },
    {
        "key": "я",
        "keyCode": "90",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "ч",
        "keyCode": "88",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "с",
        "keyCode": "67",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "м",
        "keyCode": "86",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "и",
        "keyCode": "66",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "т",
        "keyCode": "78",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "ь",
        "keyCode": "77",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "б",
        "keyCode": "188",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "ю",
        "keyCode": "190",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": ".",
        "keyCode": "191",
        "row": "4",
        "group": "alphanumeric",
    },
    {
        "key": "Shift",
        "keyCode": "16",
        "row": "4",
        "group": "control",
    },
    {
        "key": "Ctrl",
        "keyCode": "17",
        "row": "5",
        "group": "control",
    },
    {
        "key": "Win",
        "keyCode": "91",
        "row": "5",
        "group": "control",
    },
    {
        "key": "Alt",
        "keyCode": "18",
        "row": "5",
        "group": "control",
    },
    {
        "key": "",
        "keyCode": "32",
        "row": "5",
        "group": "space",
    },
    {
        "key": "Alt",
        "keyCode": "18",
        "row": "5",
        "group": "control",
    },
    {
        "key": "◀",
        "keyCode": "37",
        "row": "5",
        "group": "cursor-control",
    },
    {
        "key": "▲",
        "keyCode": "38",
        "row": "5",
        "group": "cursor-control",
    },
    {
        "key": "▼",
        "keyCode": "40",
        "row": "5",
        "group": "cursor-control",
    },
    {
        "key": "▶",
        "keyCode": "39",
        "row": "5",
        "group": "cursor-control",
    },
    {
        "key": "Ctrl",
        "keyCode": "17",
        "row": "5",
        "group": "control",
    },
];